name = "create-innovations"
author = "mystic"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2e4c14aacd1881b4fad86856f01b29efb07ee47c4f209a3966240ed964a3ec4"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
