name = "create-innovations"
author = "mystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e6ee0b9d4014cb3361e0d3555afb12ed36d0d9f6264ac02358181eddc439039"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
