name = "create-innovations"
author = "mystic"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf8f0fdfa43a89d27c5ab0ff8b713e727322fff66b8bb09b7d4a12051cb2fc29"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
