name = "create-innovations"
author = "mystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "987e2240cfe7f32a1dc6ae1534c0701f40c7841c0b87036d0f7a6dfcafec9e20"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
