name = "create-innovations"
author = "mystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1597dd057bc6d2c8fc34ca1cb82851167b014d7a28cdacca88df583afb44f7d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
