name = "create-innovations"
author = "mystic"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6db579baa956ecb7c0866dee999e28c93fe92760f9fd3f7c3ebbe6ea324dbafa"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
