name = "create-innovations"
author = "mystic"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2283d5f154b9c572d445f129630c7c5ae8849c3acd7f6e2be7610a114181164c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
