name = "create-innovations"
author = "mystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5da3659fbfdd1c4cc0c9a364d0d8778f3935d2e8798eb7cb745171d66ab598dc"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
