name = "create-innovations"
author = "mystic"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2c273706b411cc98b1c086036fd334addc41177da802d58cf80008b3b036f89"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
