name = "create-innovations"
author = "mystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e04c127345830da95d7a4720af847f44f9f5257fec5e3677d88f81d839629148"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
