name = "create-innovations"
author = "mystic"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a05c24ec33bd29df2797a0ceb0c566332c23d5217ce8835d12a2fda3a4885d5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
