name = "create-innovations"
author = "mystic"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad77b01f4997aa1c9652953aaf0456cd6c12a301948f3afd9a9801ef89c38f2a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
