name = "create-innovations"
author = "mystic"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "362971df927b7ba8ec286b78d8a3682ed1b777f5ed71c3c9ddc93ed54f361a11"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
