name = "create-innovations"
author = "mystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "601fe60db444d3ef7113f2b2cb9b015325e9156dfcb8095d29d7f8909b68704e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
