name = "create-innovations"
author = "mystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce0e48daf62c108a2cdc5c5e53461b7e10646afaff69575ed80c134a0ec40c2c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
