name = "create-innovations"
author = "mystic"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "210ecf09c252abb54c9f9043e5fee2810578877c74b94598a4f8005a6de69066"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
