name = "create-innovations"
author = "mystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bb4a61dcf0db90f06cffe48bd47dc63055121ed2b3d9ac6d4222eb09e5f0044"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
